"use client";
import { useMemo, useState } from "react";
import { ImageIcon, X } from "lucide-react";
import { useTranslations } from "next-intl";
import type { GalleryImage } from "@/lib/portal/data";
import type { Platform } from "@/types/database";
export default function AnalysisGallery({ images }: { images: GalleryImage[] }) {
  const t = useTranslations("portal.gallery"); const tp = useTranslations("platforms");
  const [month, setMonth] = useState("all"); const [platform, setPlatform] = useState<Platform | "all">("all"); const [selected, setSelected] = useState<GalleryImage | null>(null);
  const months = useMemo(() => [...new Set(images.map((i) => i.periodEnd.slice(0, 7)))], [images]);
  const filtered = images.filter((i) => (month === "all" || i.periodEnd.startsWith(month)) && (platform === "all" || i.platform === platform));
  const grouped = useMemo(() => { const map = new Map<string, GalleryImage[]>(); for (const image of filtered) { const key = image.periodEnd.slice(0, 7); map.set(key, [...(map.get(key) ?? []), image]); } return [...map.entries()].sort(([a], [b]) => b.localeCompare(a)); }, [filtered]);
  const fmt = (value: string) => new Date(`${value}-01T00:00:00`).toLocaleDateString(undefined, { month: "long", year: "numeric" });
  return <section className="space-y-5"><div className="flex flex-wrap gap-2 rounded-2xl border border-white/[0.08] bg-white/[0.025] p-3"><select value={month} onChange={(e) => setMonth(e.target.value)} className="portal-glass-select"><option value="all">{t("allMonths")}</option>{months.map((m) => <option key={m} value={m}>{fmt(m)}</option>)}</select><select value={platform} onChange={(e) => setPlatform(e.target.value as Platform | "all")} className="portal-glass-select"><option value="all">{t("allPlatforms")}</option>{(["facebook", "instagram", "tiktok", "youtube"] as Platform[]).map((p) => <option key={p} value={p}>{tp(p)}</option>)}</select></div>{!filtered.length ? <div className="rounded-2xl border border-dashed border-white/[0.1] px-5 py-14 text-center text-sm text-[#77766f]"><ImageIcon className="mx-auto mb-3 size-7" />{t("empty")}</div> : <div className="space-y-8">{grouped.map(([period, periodImages]) => <section key={period} className="space-y-3"><div className="flex items-center gap-3"><h2 className="font-satoshi text-xl text-[#f0ede5]">{fmt(period)}</h2><span className="rounded-full border border-[#d8be78]/20 bg-[#d8be78]/[0.08] px-2.5 py-1 text-[10px] text-[#d8be78]">{periodImages.length}</span><span className="h-px flex-1 bg-white/[0.07]" /></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{periodImages.map((image) => <button key={image.id} type="button" onClick={() => setSelected(image)} className="group overflow-hidden rounded-2xl border border-white/[0.1] bg-white/[0.03] text-start"><img src={image.url} alt={image.filename ?? t("imageAlt")} className="aspect-[4/3] w-full object-cover transition-transform duration-500 group-hover:scale-105" /><div className="p-3"><p className="truncate text-xs text-[#e5e0d4]">{image.filename ?? image.reportTitle}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-[#85837b]">{tp(image.platform)} · {image.reportTitle}</p></div></button>)}</div></section>)}</div>}{selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4" role="dialog" aria-modal="true" onClick={() => setSelected(null)}><div className="relative max-h-[90vh] max-w-5xl" onClick={(e) => e.stopPropagation()}><button type="button" aria-label={t("close")} onClick={() => setSelected(null)} className="absolute -end-3 -top-3 rounded-full bg-white p-2 text-black"><X className="size-4" /></button><img src={selected.url} alt={selected.filename ?? t("imageAlt")} className="max-h-[85vh] rounded-xl object-contain" /></div></div>}</section>;
}
