"use client";

import { CircleDollarSign, Clock3 } from "lucide-react";
import { useTranslations } from "next-intl";
import type { ClientPaymentPlanRow } from "@/types/database";
import type { Locale } from "@/lib/i18n";
import { formatDate, formatNumber } from "@/lib/format";

export default function PaymentPlanCard({ payments, locale }: { payments: ClientPaymentPlanRow[]; locale: Locale }) {
  const t = useTranslations("portal.payments");
  if (payments.length === 0) return null;
  const latest = payments[0];
  const statusTone = latest.status === "paid" ? "text-[#67ddb5] border-[#54d8ac]/20 bg-[#54d8ac]/[0.08]" : latest.status === "overdue" ? "text-[#f19b77] border-[#ed8f6d]/20 bg-[#ed8f6d]/[0.08]" : "text-[#e2c87e] border-[#d8be78]/20 bg-[#d8be78]/[0.08]";
  return <section className="portal-payment-card portal-glass-panel relative overflow-hidden rounded-[28px] border border-[#d8be78]/20 p-4 sm:p-6"><div className="absolute -end-16 -top-20 size-48 rounded-full bg-[#8d87f5]/10 blur-3xl" /><div className="relative flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-[9px] font-semibold tracking-[0.2em] text-[#d8be78] uppercase"><CircleDollarSign className="size-3.5" />{t("eyebrow")}</p><h2 className="mt-1 font-satoshi text-xl text-[#f4f0e7]">{t("title")}</h2></div><span className={`rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase ${statusTone}`}>{t(`status.${latest.status}` as never)}</span></div><div className={`relative mt-5 grid gap-3 sm:grid-cols-2 ${latest.total_plan_price !== null ? "lg:grid-cols-4" : "lg:grid-cols-3"}`}><div className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-3"><p className="text-[9px] uppercase tracking-[0.14em] text-[#77766f]">{t("billingDate")}</p><p className="mt-1 text-sm text-white">{formatDate(latest.billing_month, locale)}</p></div><div className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-3"><p className="text-[9px] uppercase tracking-[0.14em] text-[#77766f]">{t("amount")}</p><p className="mt-1 text-sm font-semibold text-[#ead69e]">{formatNumber(latest.amount, locale)} {latest.currency}</p></div>{latest.total_plan_price !== null && <div className="rounded-2xl border border-[#8d87f5]/15 bg-[#8d87f5]/[0.055] p-3"><p className="text-[9px] uppercase tracking-[0.14em] text-[#9690dd]">{t("totalPlanPrice")}</p><p className="mt-1 text-sm font-semibold text-[#c6c1ff]">{formatNumber(latest.total_plan_price, locale)} {latest.currency}</p></div>}<div className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-3"><p className="text-[9px] uppercase tracking-[0.14em] text-[#77766f]">{t("dueDate")}</p><p className="mt-1 text-sm text-white">{formatDate(latest.due_date, locale)}</p></div></div>{latest.notes && <div className="relative mt-4 rounded-2xl border border-[#8d87f5]/15 bg-[#8d87f5]/[0.055] p-3"><p className="text-[9px] font-semibold tracking-[0.14em] text-[#aaa4ed] uppercase">{t("note")}</p><p className="mt-1.5 text-xs leading-relaxed whitespace-pre-line text-[#b8b5c6]">{latest.notes}</p></div>}{payments.length > 1 && <div className="relative mt-4 flex items-center gap-2 text-[10px] text-[#85837b]"><Clock3 className="size-3.5 text-[#bca66e]" />{t("history", { count: payments.length })}</div>}</section>;
}
