"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { useMutation } from "@tanstack/react-query";
import { Clipboard, Eye, EyeOff, KeyRound, Loader2, Mail, Pencil, Plus, ShieldCheck, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { apiDelete, apiPatch, apiPost } from "@/lib/api-client";
import type { ClientGmailRelatedAccount, ClientGmailRow } from "@/types/database";

const blankRelated = (): ClientGmailRelatedAccount => ({ id: crypto.randomUUID(), service: "", username: "", password: "" });

export default function GmailCredentialManager({ clientId, initial }: { clientId: string; initial: ClientGmailRow[] }) {
  const t = useTranslations("auth.gmail");
  const router = useRouter();
  const [rows, setRows] = useState(initial);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editing, setEditing] = useState<ClientGmailRow | null>(null);
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [notes, setNotes] = useState(""); const [related, setRelated] = useState<ClientGmailRelatedAccount[]>([blankRelated()]);
  const [visible, setVisible] = useState<Record<string, boolean>>({});
  const reset = () => { setEmail(""); setPassword(""); setNotes(""); setRelated([blankRelated()]); setEditing(null); setDialogOpen((open) => !open); };
  const save = useMutation({ mutationFn: () => editing ? apiPatch<{ account: ClientGmailRow }>(`/api/admin/gmail-accounts/${editing.id}`, { email, password, notes, relatedAccounts: related }) : apiPost<{ account: ClientGmailRow }>(`/api/admin/clients/${clientId}/gmail-accounts`, { email, password, notes, relatedAccounts: related.filter((r) => r.service.trim()) }), onSuccess: ({ account }) => { setRows((current) => editing ? current.map((r) => r.id === account.id ? account : r) : [...current, account]); toast.success(editing ? t("updated") : t("created")); reset(); router.refresh(); }, onError: () => toast.error(t("error")) });
  const remove = useMutation({ mutationFn: (id: string) => apiDelete(`/api/admin/gmail-accounts/${id}`), onSuccess: (_, id) => { setRows((current) => current.filter((r) => r.id !== id)); toast.success(t("deleted")); } });
  const startEdit = (row: ClientGmailRow) => { setEditing(row); setEmail(row.email); setPassword(row.password); setNotes(row.notes ?? ""); setRelated(row.related_accounts?.length ? row.related_accounts : [blankRelated()]); setDialogOpen(true); };
  const copy = async (value: string) => { await navigator.clipboard.writeText(value); toast.success(t("copied")); };
  const openNew = () => { setEditing(null); setEmail(""); setPassword(""); setNotes(""); setRelated([blankRelated()]); setDialogOpen(true); };
  return <Card className="liquid-card border-white/[0.06] bg-white/[0.02]"><CardHeader className="flex-row items-center justify-between"><div><CardTitle className="flex items-center gap-2 text-sm text-white"><ShieldCheck className="size-4 text-emerald-400" />{t("title")}</CardTitle><p className="mt-1 text-xs text-slate-500">{t("hint")}</p></div><KeyRound className="size-5 text-slate-500" /></CardHeader><CardContent className="space-y-4"><Button onClick={() => { reset(); setEditing(null); setEmail(""); }} className="w-full"><Plus />{t("add")}</Button>{rows.length === 0 ? <p className="py-4 text-center text-xs text-slate-500">{t("empty")}</p> : <div className="space-y-3">{rows.map((row) => <div key={row.id} className="rounded-xl border border-white/[0.07] bg-black/20 p-3"><div className="flex items-start gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-red-500/10 text-red-300"><Mail className="size-4" /></span><div className="min-w-0 flex-1"><p dir="ltr" className="truncate text-sm text-slate-100">{row.email}</p><div className="mt-1 flex items-center gap-2 text-xs text-slate-500"><span dir="ltr">{visible[row.id] ? row.password : "••••••••••"}</span><button type="button" onClick={() => setVisible((v) => ({ ...v, [row.id]: !v[row.id] }))} aria-label={t("togglePassword")} className="text-slate-400 hover:text-white">{visible[row.id] ? <EyeOff className="size-3.5" /> : <Eye className="size-3.5" />}</button><button type="button" onClick={() => copy(row.password)} aria-label={t("copyPassword")} className="text-slate-400 hover:text-white"><Clipboard className="size-3.5" /></button></div></div><Button size="icon-sm" variant="ghost" onClick={() => startEdit(row)} aria-label={t("edit")}><Pencil /></Button><Button size="icon-sm" variant="ghost" onClick={() => window.confirm(t("deleteConfirm")) && remove.mutate(row.id)} aria-label={t("delete")}><Trash2 /></Button></div>{row.related_accounts?.length > 0 && <div className="mt-3 border-t border-white/[0.06] pt-2 text-xs text-slate-400">{row.related_accounts.map((item) => <div key={item.id} className="flex items-center justify-between py-1"><span>{item.service} <span className="text-slate-600">/</span> {item.username}</span><button type="button" onClick={() => copy(item.password)} aria-label={t("copyPassword")} className="text-slate-500 hover:text-white"><Clipboard className="size-3.5" /></button></div>)}</div>}</div>)}</div>}
  <Dialog open={dialogOpen} onOpenChange={(open) => !open && reset()}><DialogContent className="vip-dialog max-h-[92vh] overflow-hidden"><DialogHeader className="shrink-0"><DialogTitle>{editing ? t("editTitle") : t("addTitle")}</DialogTitle><DialogDescription>{t("dialogHint")}</DialogDescription></DialogHeader><div className="min-h-0 flex-1 overflow-y-auto grid gap-3 pe-1"><Input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder={t("emailPlaceholder")} /><Input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder={t("passwordPlaceholder")} /><Textarea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder={t("notesPlaceholder")} /><div className="space-y-2"><p className="text-xs font-medium text-slate-400">{t("related")}</p>{related.map((item, index) => <div key={item.id} className="grid grid-cols-[1fr_1fr_1fr_auto] gap-2"><Input value={item.service} onChange={(e) => setRelated((r) => r.map((x, i) => i === index ? { ...x, service: e.target.value } : x))} placeholder={t("servicePlaceholder")} /><Input value={item.username} onChange={(e) => setRelated((r) => r.map((x, i) => i === index ? { ...x, username: e.target.value } : x))} placeholder={t("usernamePlaceholder")} /><Input type="password" value={item.password} onChange={(e) => setRelated((r) => r.map((x, i) => i === index ? { ...x, password: e.target.value } : x))} placeholder={t("passwordPlaceholder")} /><Button type="button" size="icon" variant="ghost" onClick={() => setRelated((r) => r.filter((_, i) => i !== index))} aria-label={t("removeRelated")}><X /></Button></div>)}<Button type="button" size="sm" variant="outline" onClick={() => setRelated((r) => [...r, blankRelated()])}><Plus />{t("addRelated")}</Button></div></div><DialogFooter className="shrink-0"><Button variant="outline" onClick={reset}>{t("cancel")}</Button><Button disabled={!email || !password || save.isPending} onClick={() => save.mutate()}>{save.isPending ? <Loader2 className="animate-spin" /> : <ShieldCheck />}{t("save")}</Button></DialogFooter></DialogContent></Dialog></CardContent></Card>;
}
