"use client"
import * as React from "react"
import { Select as SelectPrimitive } from "@base-ui/react/select"
import { Check, ChevronDown } from "lucide-react"
import { cn } from "@/lib/utils"
const Select = SelectPrimitive.Root
function SelectValue(props: SelectPrimitive.Value.Props) { return <SelectPrimitive.Value data-slot="select-value" {...props} /> }
function SelectTrigger({ className, children, ...props }: SelectPrimitive.Trigger.Props) { return <SelectPrimitive.Trigger data-slot="select-trigger" className={cn("liquid-glass flex h-10 w-full items-center justify-between gap-2 rounded-xl border border-white/[0.14] px-3 text-sm text-slate-100 shadow-none outline-none transition-colors hover:border-white/[0.24] hover:bg-white/[0.08] focus-visible:border-cyan-300/50 focus-visible:ring-3 focus-visible:ring-cyan-300/15 data-[popup-open]:border-cyan-300/45 data-[popup-open]:bg-white/[0.09] disabled:pointer-events-none disabled:opacity-50", className)} {...props}>{children}<SelectPrimitive.Icon render={<ChevronDown className="size-4 text-cyan-100/65" aria-hidden />} /></SelectPrimitive.Trigger> }
function SelectContent({ className, children, ...props }: SelectPrimitive.Popup.Props) { return <SelectPrimitive.Portal><SelectPrimitive.Positioner className="z-50 outline-none" sideOffset={6}><SelectPrimitive.Popup data-slot="select-content" className={cn("portal-glass-panel relative min-w-[var(--anchor-width)] overflow-hidden rounded-2xl border border-white/[0.18] p-1.5 text-slate-100 opacity-100 shadow-[0_24px_70px_rgba(2,6,23,.42),inset_0_1px_0_rgba(255,255,255,.14)] outline-none backdrop-blur-3xl backdrop-saturate-150 transition-[transform,opacity] duration-200 ease-out data-[starting-style]:translate-y-[-4px] data-[starting-style]:opacity-0 data-[ending-style]:translate-y-[-4px] data-[ending-style]:opacity-0 motion-reduce:transition-none", className)} {...props}><SelectPrimitive.List className="relative z-[1] max-h-72 overflow-y-auto">{children}</SelectPrimitive.List></SelectPrimitive.Popup></SelectPrimitive.Positioner></SelectPrimitive.Portal> }
function SelectItem({ className, children, ...props }: SelectPrimitive.Item.Props) { return <SelectPrimitive.Item data-slot="select-item" className={cn("relative flex min-h-9 cursor-default select-none items-center rounded-xl py-2 ps-3 pe-9 text-sm text-slate-200 outline-none transition-colors data-[highlighted]:bg-white/[0.12] data-[highlighted]:text-white data-[selected]:text-cyan-100 data-[disabled]:pointer-events-none data-[disabled]:opacity-50", className)} {...props}><SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText><SelectPrimitive.ItemIndicator className="absolute end-3 text-cyan-300"><Check className="size-4" /></SelectPrimitive.ItemIndicator></SelectPrimitive.Item> }
export { Select, SelectContent, SelectItem, SelectTrigger, SelectValue }
