"use client"
import * as React from "react"
import { Select as SelectPrimitive } from "@base-ui/react/select"
import { Check, ChevronDown } from "lucide-react"
import { cn } from "@/lib/utils"
const Select = SelectPrimitive.Root
function SelectValue(props: SelectPrimitive.Value.Props) { return <SelectPrimitive.Value data-slot="select-value" {...props} /> }
function SelectTrigger({ className, children, ...props }: SelectPrimitive.Trigger.Props) { return <SelectPrimitive.Trigger data-slot="select-trigger" className={cn("flex h-9 w-full items-center justify-between gap-2 rounded-md border border-input bg-transparent px-2.5 text-sm shadow-xs outline-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 disabled:pointer-events-none disabled:opacity-50", className)} {...props}>{children}<SelectPrimitive.Icon render={<ChevronDown className="size-4 text-muted-foreground" aria-hidden />} /></SelectPrimitive.Trigger> }
function SelectContent({ className, children, ...props }: SelectPrimitive.Popup.Props) { return <SelectPrimitive.Portal><SelectPrimitive.Positioner className="z-50 outline-none" sideOffset={4}><SelectPrimitive.Popup data-slot="select-content" className={cn("min-w-[var(--anchor-width)] overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md outline-none", className)} {...props}><SelectPrimitive.List className="max-h-72 overflow-y-auto">{children}</SelectPrimitive.List></SelectPrimitive.Popup></SelectPrimitive.Positioner></SelectPrimitive.Portal> }
function SelectItem({ className, children, ...props }: SelectPrimitive.Item.Props) { return <SelectPrimitive.Item data-slot="select-item" className={cn("relative flex min-h-8 cursor-default select-none items-center rounded-sm py-1.5 ps-2 pe-8 text-sm outline-none data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50", className)} {...props}><SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText><SelectPrimitive.ItemIndicator className="absolute end-2"><Check className="size-4" /></SelectPrimitive.ItemIndicator></SelectPrimitive.Item> }
export { Select, SelectContent, SelectItem, SelectTrigger, SelectValue }
